### ISSUE TITLE
Markdown linting

### ISSUE THREAD

**Issue by jdhitsolutions** [natescherer/ChangelogManagement#29]
Your markdown output doesn't meet linting standards.
![image](https://user-images.githubusercontent.com/12089920/207964211-ebf15227-e35a-436c-97bb-941e7b54cc79.png)

**Comment by natescherer** [comment]
You're not wrong, but the reference Keep A Changelog 1.0.0 document at https://raw.githubusercontent.com/olivierlacan/keep-a-changelog/main/CHANGELOG.md also violates the same linting rules.

TBH, I've just set my linter to ignore anything named CHANGELOG.md.

**Comment by natescherer** [comment]
More broadly, because I'm aiming for this module to provide compatibility with any document in the Keep a Changelog 1.0.0 format, not just documents generated and maintained by this module, I don't think that moving away from Keep a Changelog 1.0.0 and towards markdownlint recs is the right way forward (although I do wish that KaC 1.0.0 was more in line with modern MD practices).

**Comment by jdhitsolutions** [comment]
The Platyps module runs into the same linting problems. I manually correct the markdown because the warnings bug me and I can't help myself.

**Comment by natescherer** [comment]
Yeah, I wish there was a good solution here. Could always raise concerns here: https://github.com/olivierlacan/keep-a-changelog

If there were to be a Keep a Changelog 2.0.0 with improved Markdown formatting, I would absolutely update this module to support it.
